version: '3.8'
services:
  redis:
    image: redis:7.2.5
    command: 
      - redis-server
    restart: on-failure
    ports: 
      - "6379:6379"
  mysql: 
    image: mysql:8.0.37
    env-file:
      - ./.env
    restart: on-failure
    volumes:
      - mysql_data:/var/lib/mysql/data
    ports: 
      - "3306:3306"
  bot: 
    build: .
    command: sh -c "python -m main"
    env-file:
      - ./.env
    restart: always
    depends_on:
      - mysql
      - redis


volumes:
  mysql_data: