services:
  redis:
    image: redis:latest
    environment: 
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    command: 
      - redis-server
    restart: on-failure
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/data

  # mysql: 
  #   image: mysql:8.0.37
  #   # environment:
  #     # - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #     # - MYSQL_HOST=${MYSQL_HOST}
  #     # - MYSQL_PORT=${MYSQL_PORT}
  #   restart: on-failure
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports: 
  #     - "3306:3306"

  bot: 
    build: .
    command: sh -c "python -m main"
    environment:
      - TOKEN=${TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
    restart: always
    depends_on:
      # - mysql
      - redis


volumes:
  # mysql_data:
  #   driver: local
  redis_data:
    driver: local
